import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  homeSidebar: [{type: 'autogenerated', dirName: 'home'}],
  tutorialSidebar: [{type: 'autogenerated', dirName: 'tutorials'}],
  projectSidebar: [{type: 'autogenerated', dirName: 'projects'}],
};

export default sidebars;
