import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  homeSidebar: [{ type: 'autogenerated', dirName: 'home' }],
  matrixSidebar: [{ type: 'autogenerated', dirName: 'matrix' }],
  blockchainSidebar: [{ type: 'autogenerated', dirName: 'blockchain' }],
  tutorialSidebar: [{ type: 'autogenerated', dirName: 'tutorials' }],
  aiSidebar: [{ type: 'autogenerated', dirName: 'ai' }],
  gamedevSidebar: [{ type: 'autogenerated', dirName: 'gamedev' }],
  cryptoSidebar: [{ type: 'autogenerated', dirName: 'crypto' }],
  projectSidebar: [{ type: 'autogenerated', dirName: 'projects' }],
};

export default sidebars;
